[package]
name = "pastel"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = "0.12"
tokio = { version = "1.21.2", features = ["full"] }
chrono = "0.4"
log = "0.4"
fern = "0.6"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
